apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: kube-keepalived-vip
spec:
  hostNetwork: true
  privileged: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - "*"
